ModelFinetuner:
  distill_mode: false
  sentence_level_batch: true
anneal_factor: 2
embeddings:
  BertEmbeddings-0:
    bert_model_or_path: bert-base-cased
    fine_tune: true
    layers: '-1'
    pooling_operation: mean
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 256
    locked_dropout: 0.0
    relearn_embeddings: true
    sentence_loss: true
    use_cnn: false
    use_crf: false
    use_rnn: false
    word_dropout: 0.1
model_name: en-bert_phee_finetune
ner:
  Corpus: ColumnCorpus-PHEE
  tag_dictionary: resources/taggers/phee_tags.pkl
  ColumnCorpus-PHEE:
    data_folder: datasets/phee
    column_format:
      0: text
      1: ner
    tag_to_bioes: ner

target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  fine_tune_mode: true
  learning_rate: 5.0e-05
  lr_rate: 10000
  max_epochs: 20
  mini_batch_size: 32
  monitor_test: false
  save_final_model: false
  save_finetuned_embedding: true
  train_with_dev: false
  true_reshuffle: false
trainer: ModelFinetuner

